In [45]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from stargazer.stargazer import Stargazer
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif

In [46]:
df0 = pd.read_excel("../../data1/cps12.xlsx")
df0.head()

   year        ahe  bachelor  female  age
0  2012  19.230770         0       0   30
1  2012  17.548077         0       0   29
2  2012   8.547009         0       0   27
3  2012  16.826923         0       1   25
4  2012  16.346153         1       1   27

In [47]:
model0 = sm.OLS.from_formula("ahe ~ age", data=df0).fit()
print(model0.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ahe   R-squared:                       0.018
Model:                            OLS   Adj. R-squared:                  0.018
Method:                 Least Squares   F-statistic:                     140.2
Date:                Tue, 29 Sep 2026   Prob (F-statistic):           4.72e-32
Time:                        19:16:59   Log-Likelihood:                -28112.
No. Observations:                7440   AIC:                         5.623e+04
Df Residuals:                    7438   BIC:                         5.624e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6260      1.288      3.593      0.000       2.102       7.150
age            0.5118      0.043     11.840      0.000       0.427       0.597
==============================================================================
Omnibus:                     1953.812   Durbin-Watson:                   1.853
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5216.736
Skew:                           1.406   Prob(JB):                         0.00
Kurtosis:                       5.987   Cond. No.                         313.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [48]:
model1 = sm.OLS.from_formula("ahe ~ age + female + bachelor", data=df0).fit()
print(model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ahe   R-squared:                       0.180
Model:                            OLS   Adj. R-squared:                  0.180
Method:                 Least Squares   F-statistic:                     544.5
Date:                Tue, 29 Sep 2026   Prob (F-statistic):          6.50e-320
Time:                        19:17:47   Log-Likelihood:                -27443.
No. Observations:                7440   AIC:                         5.489e+04
Df Residuals:                    7436   BIC:                         5.492e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.8662      1.188      1.571      0.116      -0.462       4.194
age            0.5103      0.040     12.912      0.000       0.433       0.588
female        -3.8103      0.230    -16.596      0.000      -4.260      -3.360
bachelor       8.3186      0.227     36.584      0.000       7.873       8.764
==============================================================================
Omnibus:                     1975.582   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6089.399
Skew:                           1.360   Prob(JB):                         0.00
Kurtosis:                       6.499   Cond. No.                         316.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [49]:
model1.t_test(f"age = {model0.params['age']}")

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
c0             0.5103      0.040     -0.039      0.969       0.433       0.588
==============================================================================

In [50]:
model1.f_test("bachelor = 0, female = 0")

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=732.8623345102767, p=3.1253721294343753e-291, df_denom=7.44e+03, df_num=2>

In [51]:
R = np.zeros((2, 4))
R[0, 2] = R[1, 3] = 1

model1.f_test(R)

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=732.8623345102767, p=3.1253721294343753e-291, df_denom=7.44e+03, df_num=2>

In [52]:
r = np.zeros(2)

model1.f_test((R, r))

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=732.8623345102767, p=3.1253721294343753e-291, df_denom=7.44e+03, df_num=2>

In [53]:
df1 = pd.read_excel("../../data1/CollegeDistance.xls")
df1.head()

,female,black,hispanic,bytest,dadcoll,momcoll,ownhome,urban,cue80,stwmfg80,dist,tuition,ed,incomehi
0,0,0,0,39.15,1,0,1,1,6.2,8.09,0.2,0.88915,12,1
1,1,0,0,48.87,0,0,1,1,6.2,8.09,0.2,0.88915,12,0
2,0,0,0,48.74,0,0,1,1,6.2,8.09,0.2,0.88915,12,0
3,0,1,0,40.40,0,0,1,1,6.2,8.09,0.2,0.88915,12,0
4,1,0,0,40.48,0,0,0,1,5.6,8.09,0.4,0.88915,13,0

In [54]:
model0 = sm.OLS.from_formula("ed ~ dist", data=df1).fit()
print(model0.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     ed   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     28.48
Date:                Tue, 29 Sep 2026   Prob (F-statistic):           1.00e-07
Time:                        19:22:50   Log-Likelihood:                -7632.2
No. Observations:                3796   AIC:                         1.527e+04
Df Residuals:                    3794   BIC:                         1.528e+04
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     13.9559      0.038    369.945      0.000      13.882      14.030
dist          -0.0734      0.014     -5.336      0.000      -0.100      -0.046
==============================================================================
Omnibus:                     7187.794   Durbin-Watson:                   1.769
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              361.676
Skew:                           0.410   Prob(JB):                     2.90e-79
Kurtosis:                       1.729   Cond. No.                         3.73
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [55]:
model0.t_test("dist = -0.075")

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
c0            -0.0734      0.014      0.118      0.906      -0.100      -0.046
==============================================================================

In [56]:
model1 = sm.OLS.from_formula("ed ~ dist + female + black + hispanic", data=df1).fit()
print(model1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     ed   R-squared:                       0.022
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     21.14
Date:                Tue, 29 Sep 2026   Prob (F-statistic):           2.95e-17
Time:                        19:23:36   Log-Likelihood:                -7604.5
No. Observations:                3796   AIC:                         1.522e+04
Df Residuals:                    3791   BIC:                         1.525e+04
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     14.1082      0.054    260.962      0.000      14.002      14.214
dist          -0.0830      0.014     -6.048      0.000      -0.110      -0.056
female         0.0057      0.059      0.098      0.922      -0.109       0.121
black         -0.5614      0.076     -7.396      0.000      -0.710      -0.413
hispanic      -0.2050      0.083     -2.458      0.014      -0.369      -0.042
==============================================================================
Omnibus:                     5005.538   Durbin-Watson:                   1.776
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              338.878
Skew:                           0.387   Prob(JB):                     2.59e-74
Kurtosis:                       1.757   Cond. No.                         9.03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [57]:
model2 = sm.OLS.from_formula(
    "ed ~ dist + female + black + hispanic + momcoll + dadcoll", data=df1
).fit()
print(model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     ed   R-squared:                       0.108
Model:                            OLS   Adj. R-squared:                  0.107
Method:                 Least Squares   F-statistic:                     76.47
Date:                Tue, 29 Sep 2026   Prob (F-statistic):           1.92e-90
Time:                        19:23:56   Log-Likelihood:                -7429.4
No. Observations:                3796   AIC:                         1.487e+04
Df Residuals:                    3789   BIC:                         1.492e+04
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     13.6793      0.056    242.862      0.000      13.569      13.790
dist          -0.0504      0.013     -3.812      0.000      -0.076      -0.024
female         0.0426      0.056      0.761      0.447      -0.067       0.152
black         -0.3807      0.073     -5.199      0.000      -0.524      -0.237
hispanic      -0.0447      0.080     -0.558      0.577      -0.202       0.112
momcoll        0.6656      0.090      7.404      0.000       0.489       0.842
dadcoll        0.9946      0.078     12.676      0.000       0.841       1.148
==============================================================================
Omnibus:                      846.230   Durbin-Watson:                   1.847
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              264.507
Skew:                           0.426   Prob(JB):                     3.66e-58
Kurtosis:                       2.028   Cond. No.                         10.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [58]:
model2.t_test("dist = -0.075")

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
c0            -0.0504      0.013      1.860      0.063      -0.076      -0.024
==============================================================================

In [59]:
model3 = sm.OLS.from_formula(
    "ed ~ dist + female + black + hispanic + momcoll + dadcoll + cue80",
    data=df1,
).fit()
print(model3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     ed   R-squared:                       0.109
Model:                            OLS   Adj. R-squared:                  0.107
Method:                 Least Squares   F-statistic:                     66.18
Date:                Tue, 29 Sep 2026   Prob (F-statistic):           2.36e-90
Time:                        19:24:38   Log-Likelihood:                -7427.4
No. Observations:                3796   AIC:                         1.487e+04
Df Residuals:                    3788   BIC:                         1.492e+04
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     13.5353      0.091    148.807      0.000      13.357      13.714
dist          -0.0569      0.014     -4.182      0.000      -0.084      -0.030
female         0.0391      0.056      0.698      0.485      -0.071       0.149
black         -0.3757      0.073     -5.129      0.000      -0.519      -0.232
hispanic      -0.0568      0.080     -0.707      0.479      -0.214       0.101
momcoll        0.6719      0.090      7.474      0.000       0.496       0.848
dadcoll        1.0007      0.078     12.750      0.000       0.847       1.155
cue80          0.0204      0.010      2.016      0.044       0.001       0.040
==============================================================================
Omnibus:                      840.323   Durbin-Watson:                   1.849
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              263.564
Skew:                           0.425   Prob(JB):                     5.86e-58
Kurtosis:                       2.029   Cond. No.                         31.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [63]:
model4 = sm.OLS.from_formula(
    "ed ~ dist + female + black + hispanic + momcoll + dadcoll + cue80 + stwmfg80 + incomehi + ownhome + bytest",
    data=df1,
).fit()
print(model4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                     ed   R-squared:                       0.283
Model:                            OLS   Adj. R-squared:                  0.281
Method:                 Least Squares   F-statistic:                     135.7
Date:                Tue, 29 Sep 2026   Prob (F-statistic):          1.92e-263
Time:                        19:26:23   Log-Likelihood:                -7015.1
No. Observations:                3796   AIC:                         1.405e+04
Df Residuals:                    3784   BIC:                         1.413e+04
Df Model:                          11
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.8614      0.250     35.487      0.000       8.372       9.351
dist          -0.0308      0.012     -2.497      0.013      -0.055      -0.007
female         0.1434      0.050      2.842      0.005       0.044       0.242
black          0.3538      0.071      4.967      0.000       0.214       0.493
hispanic       0.4024      0.074      5.418      0.000       0.257       0.548
momcoll        0.3792      0.082      4.650      0.000       0.219       0.539
dadcoll        0.5699      0.074      7.731      0.000       0.425       0.714
cue80          0.0244      0.010      2.541      0.011       0.006       0.043
stwmfg80      -0.0502      0.020     -2.535      0.011      -0.089      -0.011
incomehi       0.3666      0.061      6.042      0.000       0.248       0.486
ownhome        0.1456      0.067      2.185      0.029       0.015       0.276
bytest         0.0924      0.003     29.187      0.000       0.086       0.099
==============================================================================
Omnibus:                      116.663   Durbin-Watson:                   1.928
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               98.499
Skew:                           0.326   Prob(JB):                     4.08e-22
Kurtosis:                       2.554   Cond. No.                         539.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
model4.t_test(f"dist = {model0.params['dist']}")

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
c0            -0.0308      0.012      3.450      0.001      -0.055      -0.007
==============================================================================

In [65]:
Stargazer([model0, model1, model2, model3, model4])

In [66]:
print(Stargazer([model0, model1, model2, model3, model4]).render_html())

<table style="text-align:center"><tr><td colspan="6" style="border-bottom: 1px solid black"></td></tr>
<tr><td style="text-align:left"></td><td colspan="5"><em>Dependent variable: ed</em></td></tr><tr><td style="text-align:left"></td><tr><td style="text-align:left"></td><td>(1)</td><td>(2)</td><td>(3)</td><td>(4)</td><td>(5)</td></tr>
<tr><td colspan="6" style="border-bottom: 1px solid black"></td></tr>

<tr><td style="text-align:left">Intercept</td><td>13.956<sup>***</sup></td><td>14.108<sup>***</sup></td><td>13.679<sup>***</sup></td><td>13.535<sup>***</sup></td><td>8.861<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.038)</td><td>(0.054)</td><td>(0.056)</td><td>(0.091)</td><td>(0.250)</td></tr>
<tr><td style="text-align:left">black</td><td></td><td>-0.561<sup>***</sup></td><td>-0.381<sup>***</sup></td><td>-0.376<sup>***</sup></td><td>0.354<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td>(0.076)</td><td>(0.073)</td><td>(0.073)</td><td>(0.071)</td></tr>
<tr><td style="text-align:left">bytest</td><td></td><td></td><td></td><td></td><td>0.092<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td>(0.003)</td></tr>
<tr><td style="text-align:left">cue80</td><td></td><td></td><td></td><td>0.020<sup>**</sup></td><td>0.024<sup>**</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td>(0.010)</td><td>(0.010)</td></tr>
<tr><td style="text-align:left">dadcoll</td><td></td><td></td><td>0.995<sup>***</sup></td><td>1.001<sup>***</sup></td><td>0.570<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td>(0.078)</td><td>(0.078)</td><td>(0.074)</td></tr>
<tr><td style="text-align:left">dist</td><td>-0.073<sup>***</sup></td><td>-0.083<sup>***</sup></td><td>-0.050<sup>***</sup></td><td>-0.057<sup>***</sup></td><td>-0.031<sup>**</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.014)</td><td>(0.014)</td><td>(0.013)</td><td>(0.014)</td><td>(0.012)</td></tr>
<tr><td style="text-align:left">female</td><td></td><td>0.006<sup></sup></td><td>0.043<sup></sup></td><td>0.039<sup></sup></td><td>0.143<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td>(0.059)</td><td>(0.056)</td><td>(0.056)</td><td>(0.050)</td></tr>
<tr><td style="text-align:left">hispanic</td><td></td><td>-0.205<sup>**</sup></td><td>-0.045<sup></sup></td><td>-0.057<sup></sup></td><td>0.402<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td>(0.083)</td><td>(0.080)</td><td>(0.080)</td><td>(0.074)</td></tr>
<tr><td style="text-align:left">incomehi</td><td></td><td></td><td></td><td></td><td>0.367<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td>(0.061)</td></tr>
<tr><td style="text-align:left">momcoll</td><td></td><td></td><td>0.666<sup>***</sup></td><td>0.672<sup>***</sup></td><td>0.379<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td>(0.090)</td><td>(0.090)</td><td>(0.082)</td></tr>
<tr><td style="text-align:left">ownhome</td><td></td><td></td><td></td><td></td><td>0.146<sup>**</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td>(0.067)</td></tr>
<tr><td style="text-align:left">stwmfg80</td><td></td><td></td><td></td><td></td><td>-0.050<sup>**</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td>(0.020)</td></tr>

<td colspan="6" style="border-bottom: 1px solid black"></td></tr>
<tr><td style="text-align: left">Observations</td><td>3796</td><td>3796</td><td>3796</td><td>3796</td><td>3796</td></tr><tr><td style="text-align: left">R<sup>2</sup></td><td>0.007</td><td>0.022</td><td>0.108</td><td>0.109</td><td>0.283</td></tr><tr><td style="text-align: left">Adjusted R<sup>2</sup></td><td>0.007</td><td>0.021</td><td>0.107</td><td>0.107</td><td>0.281</td></tr><tr><td style="text-align: left">Residual Std. Error</td><td>1.807 (df=3794)</td><td>1.795 (df=3791)</td><td>1.715 (df=3789)</td><td>1.714 (df=3788)</td><td>1.538 (df=3784)</td></tr><tr><td style="text-align: left">F Statistic</td><td>28.476<sup>***</sup> (df=1; 3794)</td><td>21.137<sup>***</sup> (df=4; 3791)</td><td>76.466<sup>***</sup> (df=6; 3789)</td><td>66.176<sup>***</sup> (df=7; 3788)</td><td>135.733<sup>***</sup> (df=11; 3784)</td></tr>
<tr><td colspan="6" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align: left">Note:</td><td colspan="5" style="text-align: right"><sup>*</sup>p&lt;0.1; <sup>**</sup>p&lt;0.05; <sup>***</sup>p&lt;0.01</td></tr></table>

In [67]:
res = np.full((5, 4), fill_value=np.nan)

for i, m in enumerate([model0, model1, model2, model3, model4]):
    res[i, 0] = m.rsquared
    res[i, 1] = m.rsquared_adj
    res[i, 2] = m.aic
    res[i, 3] = m.bic

pd.DataFrame(res, columns=np.array(["R2", "R2adj", "AIC", "BIC"]))

         R2     R2adj           AIC           BIC
0  0.007450  0.007188  15268.363068  15280.846474
1  0.021816  0.020784  15219.018444  15250.226959
2  0.108008  0.106596  14872.870595  14916.562518
3  0.108964  0.107318  14870.799821  14920.733446
4  0.282935  0.280850  14054.242508  14129.142946

In [68]:
df2 = pd.read_excel("../../data1/Growth.xlsx")
df2.head()

d:\Serpentarium\Эконометрика\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,country_name,growth,oil,rgdp60,tradeshare,yearsschool,rev_coups,assasinations
0,India,1.915168,0,765.999817,0.140502,1.45,0.133333,0.866667
1,Argentina,0.617645,0,4462.001465,0.156623,4.99,0.933333,1.933333
2,Japan,4.304759,0,2953.999512,0.157703,6.71,0.000000,0.200000
3,Brazil,2.930097,0,1783.999878,0.160405,2.89,0.100000,0.100000
4,United States,1.712265,0,9895.003906,0.160815,8.66,0.000000,0.433333

In [69]:
df2.drop("country_name", axis=1).corr()

,growth,oil,rgdp60,tradeshare,yearsschool,rev_coups,assasinations
growth,1.000000,NaN,0.062708,0.351682,0.330999,-0.285622,-0.150652
oil,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rgdp60,0.062708,NaN,1.000000,-0.153231,0.821148,-0.377262,-0.087869
tradeshare,0.351682,NaN,-0.153231,1.000000,-0.011311,-0.219323,-0.316384
yearsschool,0.330999,NaN,0.821148,-0.011311,1.000000,-0.334129,-0.125189
rev_coups,-0.285622,NaN,-0.377262,-0.219323,-0.334129,1.000000,0.490170
assasinations,-0.150652,NaN,-0.087869,-0.316384,-0.125189,0.490170,1.000000

In [70]:
model0 = sm.OLS.from_formula(
    "growth ~ tradeshare + yearsschool + rev_coups + assasinations + rgdp60",
    data=df2.loc[df2.country_name != "Malta"],
).fit()
print(model0.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 growth   R-squared:                       0.291
Model:                            OLS   Adj. R-squared:                  0.230
Method:                 Least Squares   F-statistic:                     4.764
Date:                Tue, 29 Sep 2026   Prob (F-statistic):            0.00103
Time:                        19:35:12   Log-Likelihood:                -117.49
No. Observations:                  64   AIC:                             247.0
Df Residuals:                      58   BIC:                             259.9
Df Model:                           5
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.6269      0.783      0.801      0.427      -0.941       2.194
tradeshare        1.3408      0.960      1.397      0.168      -0.581       3.263
yearsschool       0.5642      0.143      3.943      0.000       0.278       0.851
rev_coups        -2.1504      1.119     -1.922      0.059      -4.390       0.089
assasinations     0.3226      0.488      0.661      0.511      -0.654       1.299
rgdp60           -0.0005      0.000     -3.059      0.003      -0.001      -0.000
==============================================================================
Omnibus:                        7.569   Durbin-Watson:                   2.130
Prob(Omnibus):                  0.023   Jarque-Bera (JB):                8.597
Skew:                           0.494   Prob(JB):                       0.0136
Kurtosis:                       4.499   Cond. No.                     2.59e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.59e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [72]:
model0.f_test("rev_coups = 0, assasinations = 0")

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=1.8671602644379444, p=0.16373378855032109, df_denom=58, df_num=2>

In [ ]:
R = np.hstack([np.zeros((4, 2)), np.eye(4)])
model0.f_test(R)

In [73]:
for i in range(1, model0.model.exog.shape[1]):
    vif_est = vif(model0.model.exog, i)
    print(f"{model0.params.index[i]:8}: {vif_est:5.4f}")

tradeshare: 1.1920
yearsschool: 3.3125
rev_coups: 1.5776
assasinations: 1.4425
rgdp60  : 3.5906

# Инструментальные переменные

```python
class statsmodels.sandbox.regression.gmm.IV2SLS(
  endog, 
  exog, 
  instrument=None
)
```

Все переменные `exog` инструментируются на все переменные в массиве `instrument`.
Если какие-то переменные из `exog` не должны быть инструментированы, то они должны быть включены в `instrument`.

Пусть мы оцениваем регрессию `ed` на `dist` и `bytest`.
Предположим, что у нас есть подозрения на эндогенность `bytest`; предполагаем, что инструментами для `bytest` будут `dadcoll`, `momcoll`, `black` и `hispanic`.

In [74]:
import statsmodels.sandbox.regression.gmm as sandbox

y = df1.ed
X_iv = sm.add_constant(df1[["dist", "bytest"]])
Instr = df1[
    ["dist", "dadcoll", "momcoll", "black", "hispanic"]
]  # Мы не инструментируем dist, поэтому добавляем его в Instr!

model_iv = sandbox.IV2SLS(y, X_iv, Instr)
model_iv_est = model_iv.fit()
print(model_iv_est.summary())

                          IV2SLS Regression Results
==============================================================================
Dep. Variable:                     ed   R-squared:                       0.122
Model:                         IV2SLS   Adj. R-squared:                  0.122
Method:                     Two Stage   F-statistic:                     227.3
                        Least Squares   Prob (F-statistic):           5.84e-94
Date:                Tue, 29 Sep 2026
Time:                        19:45:16
No. Observations:                3796
Df Residuals:                    3793
Df Model:                           2
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.1926      0.377     19.085      0.000       6.454       7.931
dist          -0.1672      0.016    -10.394      0.000      -0.199      -0.136
bytest         0.1425      0.007     19.072      0.000       0.128       0.157
==============================================================================
Omnibus:                       15.005   Durbin-Watson:                   1.744
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               15.098
Skew:                           0.154   Prob(JB):                     0.000527
Kurtosis:                       3.014   Cond. No.                         310.
==============================================================================

Тест на слабые инструменты и тест на сверхидентифицирующие ограничения придется проводить вручную.

**Так как модуль, где располагается этот класс называется `sandbox`, я подозреваю, что использовать его опасно!**

## Пакет `linearmodels`

А можно воспользоваться пакетом `linearmodels`, который расширяет пакет `statsmodels`, и в котором уже есть все необходимое.

```python
class linearmodels.iv.model.IV2SLS(
  dependent: IVData | ndarray | DataArray | DataFrame | Series, 
  exog: IVData | ndarray | DataArray | DataFrame | Series | None, 
  endog: IVData | ndarray | DataArray | DataFrame | Series | None, 
  instruments: IVData | ndarray | DataArray | DataFrame | Series | None, 
  *, 
  weights: IVData | ndarray | DataArray | DataFrame | Series | None = None
)
```

In [75]:
from linearmodels.iv import IV2SLS

X_endog = df1.bytest  # Эндогенные переменные
X_exog = sm.add_constant(df1.dist)  # Экзогенные переменные и константа
X_instr = df1[["dadcoll", "momcoll", "black", "hispanic"]]  # Инструменты

model_iv_alt = IV2SLS(y, X_exog, X_endog, X_instr).fit()
print(model_iv_alt.summary)

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:                     ed   R-squared:                      0.2212
Estimator:                    IV-2SLS   Adj. R-squared:                 0.2208
No. Observations:                3796   F-statistic:                    343.39
Date:                Tue, Sep 29 2026   P-value (F-stat)                0.0000
Time:                        19:47:32   Distribution:                  chi2(2)
Cov. Estimator:                robust

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          7.9705     0.3347     23.813     0.0000      7.3145      8.6265
dist          -0.0438     0.0119    -3.6682     0.0002     -0.0672     -0.0204
bytest         0.1164     0.0065     17.784     0.0000      0.1035      0.1292
==============================================================================

Endogenous: bytest
Instruments: dadcoll, momcoll, black, hispanic
Robust Covariance (Heteroskedastic)
Debiased: False

Объект с оцененной моделью не содержит методов для t-теста, но его можно эмулировать, взяв корень из соответствующей статистики Вальда. Единственная проблема в том, что знак статистики нужно будет считать руками
$$sgn = \begin{cases}-1&\sqrt{W}<\text{тестируемое значение в }H_0\\1&\text{иначе}\end{cases}$$
Для t-теста на значимость знак t-статистики совпадает со знаком коэффициента.

Ключевое отличие метода `wald_test` в `linearmodels` в том, что метод принимает на вход:
* или матрицу ограничений $R$,
* или матрицу ограничений $R$ и вектор правых частей $r$,
* или строковое представление, но **ОБЯЗАТЕЛЬНО** через именованный параметр `formula`. В `statsmodels` все можно было передавать через один параметр.

Следующие варианты равноправны.

In [76]:
R = np.array([[0, 1, 0]])
(model_iv_alt.wald_test(R).stat) ** (0.5)

3.6681532149346867

In [77]:
R = np.array([[0, 1, 0]])
q = np.array([0])
(model_iv_alt.wald_test(R, q).stat) ** (0.5)

3.6681532149346867

In [78]:
(model_iv_alt.wald_test(formula="dist = 0").stat) ** (0.5)

3.6681532149346867

Для тестирования множественных гипотез просто проводим тест Вальда.

In [79]:
R = np.array([[0, 1, 0], [0, 0, 1]])
model_iv_alt.wald_test(R)

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 343.3888
P-value: 0.0000
Distributed: chi2(2)
WaldTestStatistic, id: 0x2534521c9d0

In [80]:
model_iv_alt.wald_test(formula="dist=0, bytest=0")

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 343.3888
P-value: 0.0000
Distributed: chi2(2)
WaldTestStatistic, id: 0x2534521e2d0

Протестируем на равенство произвольным числам.

In [81]:
R = np.array([[0, 1, 0], [0, 0, 1]])
q = np.array([1, 2])
model_iv_alt.wald_test(R, q)

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 86870.2636
P-value: 0.0000
Distributed: chi2(2)
WaldTestStatistic, id: 0x2534521e150

In [82]:
model_iv_alt.wald_test(formula="dist=1, bytest=2")

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 86870.2636
P-value: 0.0000
Distributed: chi2(2)
WaldTestStatistic, id: 0x2534521e1d0

Диагностика результатов регрессии первого шага.
`f.stat` --- это F-статистика в регрессии эндогенной переменной на инструменты при условии, что и эндогенная переменная, и инструменты ортогонализованы относительно экзогенных переменных.

In [83]:
model_iv_alt.first_stage.diagnostics

        rsquared  partial.rsquared  shea.rsquared     f.stat  f.pval   f.dist
bytest  0.192524          0.189454       0.189454  964.19842     0.0  chi2(4)

Эта статистика численно равна F-статистике в обычном тесте на слабые инструменты.
Следующий код это показывает:
1. `model_iv_alt.first_stage.individual` содержит результаты оценивания регрессии первого шага в виде словаря, гда ключ --- эндогенная переменная, а значения --- объекты с оцененной моделью.
   Несмотря на то, что пакет `linearmodels` рассматривается как расширение `statsmodels`, интерфейс несколько отличается;
   например, при вызове объекта с оцененной моделью выдается табличка с `summary`, а не унылая строка с названием класса и адресом в памяти.
2. в `wald_test` передана линейная гипотеза о равенстве 0 коэффициентов при инструментах.

In [84]:
model_iv_alt.first_stage.individual["bytest"]

                            OLS Estimation Summary
==============================================================================
Dep. Variable:                 bytest   R-squared:                      0.1925
Estimator:                        OLS   Adj. R-squared:                 0.1915
No. Observations:                3796   F-statistic:                    987.75
Date:                Tue, Sep 29 2026   P-value (F-stat)                0.0000
Time:                        19:58:45   Distribution:                  chi2(5)
Cov. Estimator:                robust

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          52.559     0.2225     236.21     0.0000      52.123      52.995
dist          -0.2732     0.0616    -4.4347     0.0000     -0.3940     -0.1525
dadcoll        3.3884     0.3591     9.4359     0.0000      2.6846      4.0923
momcoll        2.5065     0.4074     6.1522     0.0000      1.7080      3.3050
black         -7.5423     0.3320    -22.714     0.0000     -8.1931     -6.8915
hispanic      -4.4513     0.3706    -12.011     0.0000     -5.1777     -3.7249
==============================================================================
OLSResults, id: 0x25345344cb0

In [85]:
model_iv_alt.first_stage.individual["bytest"].wald_test(
    formula="dadcoll=momcoll=black=hispanic=0"
)

Linear Equality Hypothesis Test
H0: Linear equality constraint is valid
Statistic: 964.1984
P-value: 0.0000
Distributed: chi2(4)
WaldTestStatistic, id: 0x2534887c7d0

Тест Саргана.

In [86]:
model_iv_alt.sargan

Sargan's test of overidentification
H0: The model is not overidentified.
Statistic: 195.0810
P-value: 0.0000
Distributed: chi2(3)
WaldTestStatistic, id: 0x25348863150

## GMM

Ту же самую модель с инструментальными переменными можнео оценить при помощи Обобщенного метода моментов(GMM).

```python
class linearmodels.iv.model.IVGMM(
  dependent: IVData | ndarray | DataArray | DataFrame | Series, 
  exog: IVData | ndarray | DataArray | DataFrame | Series | None, 
  endog: IVData | ndarray | DataArray | DataFrame | Series | None, 
  instruments: IVData | ndarray | DataArray | DataFrame | Series | None, 
  *, 
  weights: IVData | ndarray | DataArray | DataFrame | Series | None = None, 
  weight_type: str = 'robust', 
  **weight_config: Any
)
```
где `dependent`, `exog`, `endog`, `instruments` имеют очевидное определение,
* `weights` --- веса для наблюдений,
* `weight_type` --- тип весовой функции
  * "unadjusted", "homoskedastic" -- Assumes moment conditions are homoskedastic,
  * "robust", "heteroskedastic" -- Allows for heteroskedasticity by not autocorrelation
  * "kernel" -- Allows for heteroskedasticity and autocorrelation
  * "clustered" -- Allows for one-way cluster dependence. Требует параметра `clusters`.

In [87]:
from linearmodels.iv import IVGMM

X_endog = df1.bytest  # Эндогенные переменные
X_exog = sm.add_constant(df1.dist)  # Экзогенные переменные и константа
X_instr = df1[["dadcoll", "momcoll", "black", "hispanic"]]  # Инструменты

model_gmm = IVGMM(y, X_exog, X_endog, X_instr, weight_type="unadjusted").fit()
print(model_gmm.summary)

                          IV-GMM Estimation Summary
==============================================================================
Dep. Variable:                     ed   R-squared:                      0.2212
Estimator:                     IV-GMM   Adj. R-squared:                 0.2208
No. Observations:                3796   F-statistic:                    343.39
Date:                Tue, Sep 29 2026   P-value (F-stat)                0.0000
Time:                        20:02:18   Distribution:                  chi2(2)
Cov. Estimator:                robust

                             Parameter Estimates
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
const          7.9705     0.3347     23.813     0.0000      7.3145      8.6265
dist          -0.0438     0.0119    -3.6682     0.0002     -0.0672     -0.0204
bytest         0.1164     0.0065     17.784     0.0000      0.1035      0.1292
==============================================================================

Endogenous: bytest
Instruments: dadcoll, momcoll, black, hispanic
GMM Covariance
Debiased: False
Robust (Heteroskedastic)

По тестам все аналогично 2SLS.